# Generated by Django 5.0.1 on 2024-04-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('note_title', models.TextField(max_length=255)),
                ('note_content', models.TextField(max_length=1024)),
            ],
        ),
    ]
